test_git_connector.name=soubor vlastností
test_git_connector.reason=manualni zasah do lokalniho gitu
